- hosts: localhost
  become: true

  collections:
    # - murznn.ddev
    # - murznn.expandrive
    - orjangj.editors

  roles:
    # - murznn.ddev
    # - murznn.expandrive
    - orjangj.editors.vscode

  tasks:
    - name: Install PPAs
      import_tasks: tasks/add-ppas.yml
      vars:
        ppas:
          - ppa:kubuntu-ppa/backports
          - ppa:jonmagon/crow-translate
          - ppa:dschopf/plasma-applet-qalculate
          - ppa:boltgolt/howdy

    - name: Install apt packages
      apt:
        pkg:
          - age
          - code
          - ksnip
          - crow-translate
          - plasma-applet-qalculate

    - name: Install snap packages
      community.general.snap:
        name:
          - zoom-client
          - spotify

    - name: Install snap classic packages
      community.general.snap:
        name:
          - chezmoi
          - kontena-lens
          - kubectl
          - skype
        classic: true

    - name: 'Cron task to rotate temp directory'
      cron:
        name: 'Cron task to rotate temp directory'
        user: '{{ ansible_config_user }}'
        minute: '3'
        hour: '2'
        day: '1'
        job: '~/bin/temp-rotate'

    - name: Install howdy package
      apt:
        pkg:
          - howdy
